### ISSUE TITLE
Add more cities/countries

### ISSUE THREAD

**Issue by FunctionalHacker** [EricZeller/flutter-world-clock-v2#13]
Thanks for the very polished app, looks very promising. However, in it's current state it's not much use for me personally because most of the cities I'm interested in are missing.
- Finland/Helsinki
- Dallas
- Seattle

**Comment by EricZeller** [comment]
Thank you for your feedback! I will add those cities with the next release `v1.4.2`, but I wanted to change the for now static JSON list of cities anyways in the future
